=== SaikiranDaripelli/WsdlAuditor/WsdlAuditor/src/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="WsdlAuditorConfiguration" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="wsdlauditorconfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="defaultoutputdir" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element name="outputusers" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="outputuser" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="class" type="xs:string" minOccurs="1" maxOccurs="1"/>
										<xs:element name="outputdir" type="xs:string" minOccurs="0" maxOccurs="1" />
										<xs:element name="param"  minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"  minOccurs="1" maxOccurs="1"/>
													<xs:element name="value" type="xs:string"  minOccurs="1" maxOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="disabled" type="xs:boolean" />
									<xs:attribute name="name" use="required" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="factory"  minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="executors"  minOccurs="0" maxOccurs="1">
								<xs:complexType >
									<xs:sequence >
										<xs:element name="executor"  minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="operator" type="xs:string"  minOccurs="1" maxOccurs="1"/>
													<xs:element name="class" type="xs:string"  minOccurs="1" maxOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="dataobjects"  minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dataobject"  minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="type" type="xs:string"  minOccurs="1" maxOccurs="1"/>
													<xs:element name="class" type="xs:string"  minOccurs="1" maxOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SaikiranDaripelli/WsdlAuditor/WsdlAuditor/target/SampleConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<wsdlauditorconfig
xmlns="WsdlAuditorConfiguration"
xmlns:xsi="http://www.w3.org/2001/XMLSchema"
xsi:schemaLocation="WsdlAuditorConfiguration Configuration.xsd">
	<defaultoutputdir>c:\wsdlAuditReports</defaultoutputdir>
	<outputusers>
		<outputuser name="DefaultHtml" disabled="false">
			<class>org.wsdl.tools.wsdlauditor.html.DefaultOutputUser</class>
			<outputdir>c:\wsdlAuditReports</outputdir>
			<param>
				<name>filename</name>
				<value>AuditReport.html</value>
			</param>
		</outputuser>
	</outputusers>
	<factory>
		<executors>
			<executor>
				<operator>Contains</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.ContainsExec
				</class>
			</executor>
			<executor>
				<operator>Count</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.CountExec
				</class>
			</executor>
			<executor>
				<operator>Direct</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.DirectReturn
				</class>
			</executor>
			<executor>
				<operator>Empty</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.EmptyExec
				</class>
			</executor>
			<executor>
				<operator>EndsWith</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.EndsWithExec
				</class>
			</executor>
			<executor>
				<operator>Equals</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.EqualsExec
				</class>
			</executor>
			<executor>
				<operator>In</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.InExec</class>
			</executor>
			<executor>
				<operator>Method</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.MethodExec
				</class>
			</executor>
			<executor>
				<operator>Matches</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.PatternExec
				</class>
			</executor>
			<executor>
				<operator>Position</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.PositionExec
				</class>
			</executor>
			<executor>
				<operator>Present</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.PresentExec
				</class>
			</executor>
			<executor>
				<operator>Primitive</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.PrimitiveExec
				</class>
			</executor>
			<executor>
				<operator>StartsWith</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.StartsWithExec
				</class>
			</executor>
			<executor>
				<operator>!Contains</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.ContainsExec
				</class>
			</executor>
			<executor>
				<operator>Direct</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.DirectReturn
				</class>
			</executor>
			<executor>
				<operator>!Empty</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.EmptyExec
				</class>
			</executor>
			<executor>
				<operator>!EndsWith</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.EndsWithExec
				</class>
			</executor>
			<executor>
				<operator>!Equals</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.EqualsExec
				</class>
			</executor>
			<executor>
				<operator>!In</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.InExec</class>
			</executor>
			<executor>
				<operator>!Matches</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.PatternExec
				</class>
			</executor>
			<executor>
				<operator>!Position</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.PositionExec
				</class>
			</executor>
			<executor>
				<operator>!Present</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.PresentExec
				</class>
			</executor>
			<executor>
				<operator>!Primitive</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.PrimitiveExec
				</class>
			</executor>
			<executor>
				<operator>!StartsWith</operator>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.executors.StartsWithExec
				</class>
			</executor>
		</executors>
		<dataobjects>
			<dataobject>
				<type>RuleEngine</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.RuleEngine</class>
			</dataobject>
			<dataobject>
				<type>ElementInfo</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.ElementInfo</class>
			</dataobject>
			<dataobject>
				<type>Error</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.Error</class>
			</dataobject>
			<dataobject>
				<type>Rule</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.Rule</class>
			</dataobject>
			<dataobject>
				<type>RuleDefinition</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.RuleDefinition
				</class>
			</dataobject>
			<dataobject>
				<type>RuleParam</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.RuleExecutorParam
				</class>
			</dataobject>
			<dataobject>
				<type>RuleGroup</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.RuleGroup</class>
			</dataobject>
			<dataobject>
				<type>Rules</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.Rules</class>
			</dataobject>
			<dataobject>
				<type>RuleSet</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.RuleSet</class>
			</dataobject>
			<dataobject>
				<type>SchemaElement</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.SchemaElement
				</class>
			</dataobject>
			<dataobject>
				<type>SchemaError</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.SchemaError</class>
			</dataobject>
			<dataobject>
				<type>WsdlSchema</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.data.WsdlSchema</class>
			</dataobject>
			<dataobject>
				<type>RuleDefinitionReader</type>
				<class>org.wsdl.tools.wsdlauditor.ruledefn.DefaultRuleDefinitionReader
				</class>
			</dataobject>
			<dataobject>
				<type>DocumentParser</type>
				<class>org.wsdl.tools.wsdlauditor.document.WsdlParser</class>
			</dataobject>
		</dataobjects>
	</factory>
</wsdlauditorconfig>
